# .vimrc-dein.toml

### important ###

[[plugins]]
repo = '~/.vim/dein/repos/github.com/Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.git'
build = 'make'

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'xolox/vim-session'
depends = ['xolox/vim-misc']

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'vim-scripts/yanktmp.vim'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javascript']


### unite ###

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['Shougo/neomru.vim', 'Shougo/neoyank.vim']

[[plugins]]
repo = 'Shougo/unite-session'
depends = ['Shougo/unite.vim']

[[plugins]]
repo = 'kannokanno/unite-dwm'
depends = ['Shougo/unite.vim']

[[plugins]]
repo = 'tacroe/unite-mark'
depends = ['Shougo/unite.vim']


### colorscheme ###

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'vim-scripts/badwolf'

[[plugins]]
repo = 'vim-scripts/molokai'

[[plugins]]
repo = 'vim-scripts/Lucius'

[[plugins]]
repo = 'vim-scripts/Zenburn'

[[plugins]]
repo = 'yuroyoro/yuroyoro256.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'


### syntax ###

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'
depends = ['pangloss/vim-javascript']

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
depends = ['leafgarland/typescript-vim']

[[plugins]]
repo = 'vim-scripts/JSON.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'JulesWang/css.vim'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'stephpy/vim-yaml'

[[plugins]]
repo = 'tikhomirov/vim-glsl'

[[plugins]]
repo = 'autowitch/hive.vim'

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'vim-scripts/jQuery'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python', 'python3', 'djangohtml']

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript', 'html']


### shougo ###

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neosnippet.vim.git'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = ''' (has('nvim') || has('python3')) && system('pip3 show neovim') !=# '' '''


### misc ###

[[plugins]]
repo = 'groenewege/vim-less'

[[plugins]]
repo = 'vim-scripts/eregex.vim'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'vim-scripts/gitv'

#[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo = 'sjl/gundo.vim.git'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'vim-scripts/closetag.vim'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'wesleyche/SrcExpl'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'vim-scripts/linediff.vim'

[[plugins]]
repo = 'vim-scripts/camelcasemotion'

[[plugins]]
repo = 'vim-scripts/renamer.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'terryma/vim-expand-region'
