# .vimrc-dein.toml

[[plugins]]
repo = '~/.vim/dein/repos/github.com/Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.git'
build = 'make'

[[plugins]]
repo = 'vim-scripts/Lucius'

[[plugins]]
repo = 'vim-scripts/Zenburn'

[[plugins]]
repo = 'vim-scripts/molokai'

[[plugins]]
repo = 'yuroyoro/yuroyoro256.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'vim-scripts/JSON.vim'

[[plugins]]
repo = 'groenewege/vim-less'

[[plugins]]
repo = 'autowitch/hive.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'JulesWang/css.vim'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'stephpy/vim-yaml'

[[plugins]]
repo = 'tikhomirov/vim-glsl'

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'vim-scripts/jQuery'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['Shougo/neomru.vim', 'Shougo/neoyank.vim']

[[plugins]]
repo = 'Shougo/unite-session'
depends = ['Shougo/unite.vim']

[[plugins]]
repo = 'kannokanno/unite-dwm'
depends = ['Shougo/unite.vim']

[[plugins]]
repo = 'tacroe/unite-mark'
depends = ['Shougo/unite.vim']

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'xolox/vim-session'
depends = ['xolox/vim-misc']

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#depends = 'context_filetype.vim'
#on_i = 1
#if = ''' (has('nvim') || has('python3')) && system('pip3 show neovim') !=# '' '''
#hook_source = '''
#    let g:deoplete#enable_at_startup = 1
#    let g:deoplete#enable_ignore_case = 1
#    let g:deoplete#enable_smart_case = 1
#'''

#[[plugins]]
#repo = 'Shougo/neocomplete'
#on_i = 1
#if = ''' has('lua') '''

[[plugins]]
repo = 'Shougo/neocomplcache'
on_i = 1
#if = ''' !has('lua') || !has('nvim') || !(has('python3')) && system('pip3 show neovim') !=# '') '''

[[plugins]]
repo = 'Shougo/neosnippet.vim.git'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-scripts/eregex.vim'

[[plugins]]
repo = 'vim-scripts/yanktmp.vim'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'vim-scripts/gitv'

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo = 'sjl/gundo.vim.git'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'vim-scripts/closetag.vim'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'wesleyche/SrcExpl'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'vim-scripts/linediff.vim'

[[plugins]]
repo = 'vim-scripts/camelcasemotion'

[[plugins]]
repo = 'vim-scripts/renamer.vim'

[[plugins]]
repo = 'vim-scripts/open-browser.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python', 'python3', 'djangohtml']

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript', 'html']

[[plugins]]
repo = 'LeafCage/yankround.vim'


# nouse
#[[plugins]]
#repo = 'maxmellon/vim-jsx-pretty'
#
#[[plugins]]
#repo = 'othree/es.next.syntax.vim'
#
#[[plugins]]
#repo = 'othree/javascript-libraries-syntax.vim'
#
#[[plugins]]
#repo = 'pangloss/vim-javascript'
#
#[[plugins]]
#repo = 'taglist.vim'
#
#[[plugins]]
#repo = 'spolu/dwm.vim'
#
#[[plugins]]
#repo = 'bronson/vim-tailing-whitespace'
#
#[[plugins]]
#repo = 'sindrenm/angular.vim'
#
#[[plugins]]
#repo = 'VimRepress'
#
#[[plugins]]
#repo = 'nathanaelkane/vim-indent-guides'
#
#[[plugins]]
#repo = 'kevinw/pyflakes-vim'
#
#[[plugins]]
#repo = 'mitechie/pyflakes-pathogen'
#
#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#
#[[plugins]]
#repo = 'kana/vim-smartinput'
#
#[[plugins]]
#repo = 'othree/html5.vim'
#
#[[plugins]]
#repo = 'jelera/vim-javascript-syntax'
#
#[[plugins]]
#repo = 'kakkyz81/evervim'
#
#[[plugins]]
#repo = 'mattn/benchvimrc-vim'
#
#[[plugins]]
#repo = 'scrooloose/nerdtree'
#
#[[plugins]]
#repo = 'terryma/vim-multiple-cursors'
#
#[[plugins]]
#repo = '5t111111/neat-json.vim'
#
#[[plugins]]
#repo = 'thinca/vim-qfreplace'
#
#[[plugins]]
#repo = 'glidenote/memolist.vim'
#
#[[plugins]]
#repo = 'Shougo/vimshell.git'
#
#[[plugins]]
#repo = 'fuenor/qfixgrep'
#
#[[plugins]]
#repo = 'occur.vim'
#
#[[plugins]]
#repo = 'tpope/vim-fugitive'
#
#[[plugins]]
#repo = 'dbext.vim'
#
#[[plugins]]
#repo = 'scratch.vim'
#
#[[plugins]]
#repo = 'quickrun.vim'
#
#[[plugins]]
#repo = 'vimgrep.vim'
#
#[[plugins]]
#repo = 'scrooloose/syntastic'
#
#[[plugins]]
#repo = 'nathanaelkane/vim-indent-guides'
#
#[[plugins]]
#repo = 'editorconfig/editorconfig-vim'

#[[plugins]]
#repo = 'vim-scripts/VimRepress'
#gui = 1
#
#[[plugins]]
#repo = 'vim-scripts/minibufexpl.vim'
#gui = 1
#
#[[plugins]]
#repo = 'vim-scripts/bufferlist.vim'
#gui = 1

